# ==============================================================
# Example YAML values for typical kubeview deployment scenarios
# ==============================================================

# If true the app will function in single namespace mode
limitNamespace: false

# Networking - expose using an ingress
# Note. If both ingress and loadbalancer are disabled, an internal ClusterIP service will be created
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: kubeview.example.net
  # tls:
  #  - secretName: my-cert
  #    hosts:
  #      - kubeview.example.net

# Networking - expose using simple load balancer
loadBalancer:
  enabled: false
  # If you have an existing IP you can set it here
  # IP: "48.211.176.163"
